"""
Augment chatbot_intents.json with more examples for weak classes, then retrain.
"""

import json
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DATA_FILE = BASE_DIR / "data" / "chatbot_intents.json"

with open(DATA_FILE, "r", encoding="utf-8") as f:
    data = json.load(f)

existing = {(item["text"].strip().lower(), item["intent"]) for item in data}

new_examples = [
    # competitive_intelligence (34 -> ~64)
    ("Who are my main competitors in this space?", "competitive_intelligence"),
    ("How do I do a competitive analysis?", "competitive_intelligence"),
    ("What is my competitive moat?", "competitive_intelligence"),
    ("How do I differentiate from competitors?", "competitive_intelligence"),
    ("Map out my competitive landscape.", "competitive_intelligence"),
    ("Who else is solving this problem?", "competitive_intelligence"),
    ("What are my competitors doing differently?", "competitive_intelligence"),
    ("Compare my startup to the competition.", "competitive_intelligence"),
    ("How do I win against established players?", "competitive_intelligence"),
    ("What is my unfair advantage over rivals?", "competitive_intelligence"),
    ("Analyze my top three competitors.", "competitive_intelligence"),
    ("How does my pricing compare to competitors?", "competitive_intelligence"),
    ("Who are the emerging threats in my market?", "competitive_intelligence"),
    ("What is the competitive landscape like?", "competitive_intelligence"),
    ("Are there any indirect competitors I should watch?", "competitive_intelligence"),
    ("How do I track competitor moves?", "competitive_intelligence"),
    ("What can I learn from my competitors failures?", "competitive_intelligence"),
    ("Benchmark my product against the competition.", "competitive_intelligence"),
    ("Who is winning in my market segment?", "competitive_intelligence"),
    ("What are my competitors spending on marketing?", "competitive_intelligence"),
    ("How do I build a competitive moat?", "competitive_intelligence"),
    ("Are we better than the competition?", "competitive_intelligence"),
    ("What is competitor X doing that we are not?", "competitive_intelligence"),
    ("How saturated is my competitive landscape?", "competitive_intelligence"),
    ("What are the barriers to entry for competitors?", "competitive_intelligence"),
    ("Is my product truly differentiated?", "competitive_intelligence"),
    ("Who would buy from a competitor instead of us?", "competitive_intelligence"),
    ("What do customers say about my competitors?", "competitive_intelligence"),
    ("How do competitors price their product?", "competitive_intelligence"),
    ("What features do competitors have that we lack?", "competitive_intelligence"),

    # investor_readiness (30 -> ~60)
    ("Are we ready for institutional investors?", "investor_readiness"),
    ("What do investors look for in a cap table?", "investor_readiness"),
    ("Is my company investable right now?", "investor_readiness"),
    ("How do I get investor ready in 90 days?", "investor_readiness"),
    ("What metrics matter most to investors?", "investor_readiness"),
    ("Do I need a board before raising?", "investor_readiness"),
    ("How do I prepare a data room?", "investor_readiness"),
    ("What should my financials look like for investors?", "investor_readiness"),
    ("Are our unit economics good enough for VCs?", "investor_readiness"),
    ("How do I value my company for investors?", "investor_readiness"),
    ("What stage do I need to be at for angels?", "investor_readiness"),
    ("How do I create an investor update?", "investor_readiness"),
    ("Should I warm up investors before raising?", "investor_readiness"),
    ("What legal docs do I need before fundraising?", "investor_readiness"),
    ("How do I build relationships with VCs?", "investor_readiness"),
    ("Is my traction enough for seed investors?", "investor_readiness"),
    ("What do investors think about my market?", "investor_readiness"),
    ("How do I pass due diligence?", "investor_readiness"),
    ("What are red flags for investors?", "investor_readiness"),
    ("How important is team for investor decisions?", "investor_readiness"),
    ("Do I need a lead investor?", "investor_readiness"),
    ("How do I choose the right investors?", "investor_readiness"),
    ("What is a typical seed round structure?", "investor_readiness"),
    ("Should I raise from angels or VCs first?", "investor_readiness"),
    ("How long does due diligence take?", "investor_readiness"),
    ("What documents are in a data room?", "investor_readiness"),
    ("How do I prepare for investor meetings?", "investor_readiness"),
    ("What questions will investors ask me?", "investor_readiness"),
    ("How do I handle investor rejections?", "investor_readiness"),
    ("Should I raise a note or a round?", "investor_readiness"),

    # market_timing (25 -> ~60)
    ("Is now a good time to launch my startup?", "market_timing"),
    ("Should I wait for the market to mature?", "market_timing"),
    ("Is this the right moment to enter the market?", "market_timing"),
    ("Are we ahead of the market curve?", "market_timing"),
    ("Is the market ready for what we are building?", "market_timing"),
    ("How do I know if the timing is right?", "market_timing"),
    ("Are we too late for this opportunity?", "market_timing"),
    ("What market trends should I consider for timing?", "market_timing"),
    ("Should I launch now or wait?", "market_timing"),
    ("How does market timing affect fundraising?", "market_timing"),
    ("Is there a window of opportunity right now?", "market_timing"),
    ("What is the best season to launch?", "market_timing"),
    ("Are macro conditions right for my startup?", "market_timing"),
    ("How do market cycles affect my startup?", "market_timing"),
    ("Is this a good time to raise capital?", "market_timing"),
    ("Should I pivot based on market timing?", "market_timing"),
    ("How do I know if I am too early?", "market_timing"),
    ("What signals indicate the market is ready?", "market_timing"),
    ("Is the economy good for startups right now?", "market_timing"),
    ("How does timing affect my go-to-market strategy?", "market_timing"),
    ("Should I accelerate my launch timeline?", "market_timing"),
    ("What happens if I launch too early?", "market_timing"),
    ("How do I assess market readiness?", "market_timing"),
    ("Is there a first-mover advantage here?", "market_timing"),
    ("Am I better as a fast follower?", "market_timing"),
    ("What is the market adoption rate?", "market_timing"),
    ("How do I time my fundraising round?", "market_timing"),
    ("Are we early enough to capture the market?", "market_timing"),
    ("Should we soft launch to test timing?", "market_timing"),
    ("What macroeconomic factors affect my launch?", "market_timing"),
    ("Is investor sentiment favorable right now?", "market_timing"),
    ("How do market trends affect my runway planning?", "market_timing"),
    ("Should I wait for regulatory clarity?", "market_timing"),
    ("Is the market growing or shrinking?", "market_timing"),
    ("How do I validate market timing with customers?", "market_timing"),

    # market_validation (30 -> ~60)
    ("How do I validate my startup idea?", "market_validation"),
    ("Is there real demand for my product?", "market_validation"),
    ("How do I test product-market fit?", "market_validation"),
    ("What experiments should I run to validate?", "market_validation"),
    ("How many customer interviews is enough?", "market_validation"),
    ("How do I know if people will pay for this?", "market_validation"),
    ("What is the best way to validate a B2B idea?", "market_validation"),
    ("Should I build an MVP to validate?", "market_validation"),
    ("How do I measure product-market fit?", "market_validation"),
    ("What metrics show market validation?", "market_validation"),
    ("How do I validate pricing?", "market_validation"),
    ("What is willingness to pay for my solution?", "market_validation"),
    ("Should I run a landing page test?", "market_validation"),
    ("How do I find early adopters?", "market_validation"),
    ("Is pre-selling a good validation strategy?", "market_validation"),
    ("How do I validate my target market size?", "market_validation"),
    ("What are signals of strong product-market fit?", "market_validation"),
    ("How do I validate my solution before building?", "market_validation"),
    ("Should I build a prototype first?", "market_validation"),
    ("How do I conduct customer discovery?", "market_validation"),
    ("What questions should I ask in validation interviews?", "market_validation"),
    ("How do I validate my value proposition?", "market_validation"),
    ("Is a landing page with signups enough validation?", "market_validation"),
    ("How do I validate across different segments?", "market_validation"),
    ("What is the minimum validation I need before building?", "market_validation"),
    ("How do I validate without spending money?", "market_validation"),
    ("What are common validation mistakes?", "market_validation"),
    ("How long should validation take?", "market_validation"),
    ("How do I validate a marketplace idea?", "market_validation"),
    ("Should I validate both sides of the marketplace?", "market_validation"),

    # risk_assessment (34 -> ~64)
    ("What are the top risks for my startup right now?", "risk_assessment"),
    ("How do I assess risk in my business?", "risk_assessment"),
    ("What keeps you up at night about my startup?", "risk_assessment"),
    ("Identify the biggest threats to my business.", "risk_assessment"),
    ("What are the operational risks I should address?", "risk_assessment"),
    ("How do I create a risk mitigation plan?", "risk_assessment"),
    ("What financial risks should I worry about?", "risk_assessment"),
    ("What market risks could kill my startup?", "risk_assessment"),
    ("How do I build a risk register?", "risk_assessment"),
    ("What are the technical risks in my stack?", "risk_assessment"),
    ("How vulnerable is my startup to competition?", "risk_assessment"),
    ("What regulatory risks apply to my business?", "risk_assessment"),
    ("How do I prioritize risks?", "risk_assessment"),
    ("What is my biggest exposure right now?", "risk_assessment"),
    ("How do I reduce risk in my business model?", "risk_assessment"),
    ("What are the risks of scaling too fast?", "risk_assessment"),
    ("How do I hedge against market downturns?", "risk_assessment"),
    ("What people risks does my team face?", "risk_assessment"),
    ("How do I mitigate key person risk?", "risk_assessment"),
    ("What risks come with our current burn rate?", "risk_assessment"),
    ("How do I stress-test my business model?", "risk_assessment"),
    ("What are our single points of failure?", "risk_assessment"),
    ("What concentration risks do we have?", "risk_assessment"),
    ("How do I protect against IP risks?", "risk_assessment"),
    ("What are the risks of our pricing model?", "risk_assessment"),
    ("How exposed are we to supplier risk?", "risk_assessment"),
    ("What technology risks should I address?", "risk_assessment"),
    ("How do I manage risk while innovating?", "risk_assessment"),
    ("What are the worst case scenarios?", "risk_assessment"),
    ("How do I build a risk-aware culture?", "risk_assessment"),

    # startup_health (15 -> ~60)
    ("How healthy is my startup overall?", "startup_health"),
    ("Give me a complete startup health check.", "startup_health"),
    ("Is my startup in good shape?", "startup_health"),
    ("Rate the overall health of my business.", "startup_health"),
    ("How do I measure startup health?", "startup_health"),
    ("What is my startup health score?", "startup_health"),
    ("Is my business viable long term?", "startup_health"),
    ("Run a full health assessment on my startup.", "startup_health"),
    ("What are the key indicators of startup health?", "startup_health"),
    ("How do I know if my startup is failing?", "startup_health"),
    ("What is the pulse of my startup right now?", "startup_health"),
    ("Is my startup on track for success?", "startup_health"),
    ("How do I benchmark my startup health?", "startup_health"),
    ("What is a healthy startup look like?", "startup_health"),
    ("Are we in the danger zone?", "startup_health"),
    ("How do I improve my startup health?", "startup_health"),
    ("What metrics define a healthy startup?", "startup_health"),
    ("Diagnose my startup health issues.", "startup_health"),
    ("Is my burn rate healthy?", "startup_health"),
    ("Am I growing fast enough to be healthy?", "startup_health"),
    ("What is the temperature of my startup?", "startup_health"),
    ("Give me a founder health check.", "startup_health"),
    ("How resilient is my startup?", "startup_health"),
    ("What is the overall health score?", "startup_health"),
    ("Check all vital signs of my startup.", "startup_health"),
    ("Is my unit economics healthy?", "startup_health"),
    ("How healthy is my revenue growth?", "startup_health"),
    ("Assess my startup viability.", "startup_health"),
    ("Are we a healthy startup or struggling?", "startup_health"),
    ("What is the health of my market position?", "startup_health"),
    ("How healthy is our customer acquisition?", "startup_health"),
    ("Is our team structure healthy?", "startup_health"),
    ("How do I fix an unhealthy startup?", "startup_health"),
    ("What are red flags in my startup health?", "startup_health"),
    ("Is our churn rate healthy?", "startup_health"),
    ("What healthy growth rate should I target?", "startup_health"),
    ("Are our margins healthy?", "startup_health"),
    ("How healthy is our cash position?", "startup_health"),
    ("Is our runway healthy?", "startup_health"),
    ("Give my startup a health score out of 10.", "startup_health"),
    ("What is my startup diagnosis?", "startup_health"),
    ("How do I know if I am building something viable?", "startup_health"),
    ("Is my startup model sustainable?", "startup_health"),
    ("What are the signs of a dying startup?", "startup_health"),
    ("Am I on the right track?", "startup_health"),

    # swot_analysis (26 -> ~60)
    ("Run a SWOT analysis for my startup.", "swot_analysis"),
    ("What are my biggest strengths?", "swot_analysis"),
    ("What are my critical weaknesses?", "swot_analysis"),
    ("Where are the opportunities for my startup?", "swot_analysis"),
    ("What threats should I watch out for?", "swot_analysis"),
    ("SWOT my business please.", "swot_analysis"),
    ("Break down my strengths and weaknesses.", "swot_analysis"),
    ("What opportunities can I capitalize on?", "swot_analysis"),
    ("What external threats could hurt me?", "swot_analysis"),
    ("Analyze my startup using SWOT framework.", "swot_analysis"),
    ("Help me identify my competitive strengths.", "swot_analysis"),
    ("What are my hidden weaknesses?", "swot_analysis"),
    ("What market opportunities should I pursue?", "swot_analysis"),
    ("What threats are emerging in my market?", "swot_analysis"),
    ("Give me a strategic SWOT analysis.", "swot_analysis"),
    ("What are my internal strengths?", "swot_analysis"),
    ("What internal weaknesses hold me back?", "swot_analysis"),
    ("What external opportunities can I leverage?", "swot_analysis"),
    ("What external threats keep me up at night?", "swot_analysis"),
    ("SWOT analysis for my business model.", "swot_analysis"),
    ("Analyze my competitive position using SWOT.", "swot_analysis"),
    ("What is my SWOT profile?", "swot_analysis"),
    ("Do a strategic SWOT for my startup.", "swot_analysis"),
    ("Highlight my top three strengths.", "swot_analysis"),
    ("Identify my top three weaknesses.", "swot_analysis"),
    ("What strengths differentiate me?", "swot_analysis"),
    ("What weaknesses do I need to address urgently?", "swot_analysis"),
    ("Where should I focus my SWOT efforts?", "swot_analysis"),
    ("What does my SWOT tell me?", "swot_analysis"),
    ("How do I use SWOT to plan strategy?", "swot_analysis"),
    ("Give me an honest SWOT assessment.", "swot_analysis"),
    ("What are the opportunities I am missing?", "swot_analysis"),
    ("What threats are about to hit my market?", "swot_analysis"),
    ("SWOT me.", "swot_analysis"),

    # team_health (34 -> ~60)
    ("How strong is my founding team?", "team_health"),
    ("Do we have the right talent on the team?", "team_health"),
    ("What skills are missing from my team?", "team_health"),
    ("How do I build a stronger team?", "team_health"),
    ("Is our team balanced enough?", "team_health"),
    ("Should I hire a CTO?", "team_health"),
    ("How do I attract top talent?", "team_health"),
    ("What is the right team size for my stage?", "team_health"),
    ("How do I evaluate team performance?", "team_health"),
    ("Are we lacking any key roles?", "team_health"),
    ("How do I build company culture?", "team_health"),
    ("Is our team aligned on the vision?", "team_health"),
    ("How do I handle team conflict?", "team_health"),
    ("What is team cohesion and why does it matter?", "team_health"),
    ("How do I know if I have the right co-founder?", "team_health"),
    ("Should I replace a underperforming team member?", "team_health"),
    ("How do I motivate my team?", "team_health"),
    ("What equity should I offer early hires?", "team_health"),
    ("How do I assess founder-market fit?", "team_health"),
    ("Is my advisory board strong enough?", "team_health"),
    ("How do I find a technical co-founder?", "team_health"),
    ("What makes a great startup team?", "team_health"),
    ("How do I scale my team as we grow?", "team_health"),
    ("What team metrics matter most?", "team_health"),
    ("How do I retain key employees?", "team_health"),
    ("Should I hire for experience or potential?", "team_health"),

    # traction_analysis (31 -> ~60)
    ("How is our user growth trending?", "traction_analysis"),
    ("What is our month-over-month growth?", "traction_analysis"),
    ("Are we growing fast enough?", "traction_analysis"),
    ("What are our key traction metrics?", "traction_analysis"),
    ("How do I measure traction?", "traction_analysis"),
    ("What traction do investors want to see?", "traction_analysis"),
    ("Is our growth rate healthy?", "traction_analysis"),
    ("How do I improve customer retention?", "traction_analysis"),
    ("What is our activation rate?", "traction_analysis"),
    ("Are users sticking around?", "traction_analysis"),
    ("How do I drive more engagement?", "traction_analysis"),
    ("What is our viral coefficient?", "traction_analysis"),
    ("How do I improve our conversion funnel?", "traction_analysis"),
    ("What is our customer acquisition cost trending?", "traction_analysis"),
    ("How does our traction compare to benchmarks?", "traction_analysis"),
    ("Are we seeing product-market fit signals?", "traction_analysis"),
    ("How do I accelerate our growth?", "traction_analysis"),
    ("What is our weekly active user count?", "traction_analysis"),
    ("How do I reduce churn?", "traction_analysis"),
    ("What is our net dollar retention?", "traction_analysis"),
    ("How do we get our first 100 customers?", "traction_analysis"),
    ("How do we get to 1000 users?", "traction_analysis"),
    ("What growth channels are working best?", "traction_analysis"),
    ("How do I measure product engagement?", "traction_analysis"),
    ("What is our daily active user count?", "traction_analysis"),
    ("How do we improve our NPS?", "traction_analysis"),
    ("What is our customer lifetime value?", "traction_analysis"),
    ("How do I prove traction to investors?", "traction_analysis"),
    ("Are we seeing repeat usage?", "traction_analysis"),

    # runway_analysis (54 -> ~60)
    ("How long will our current runway last?", "runway_analysis"),
    ("We have $150K left, what is our runway?", "runway_analysis"),
    ("How do I extend my runway?", "runway_analysis"),
    ("How much cash do we have in the bank?", "runway_analysis"),
    ("When will we run out of money?", "runway_analysis"),
    ("How do I calculate runway?", "runway_analysis"),
]

seen = set(existing)
added = 0
for text, intent in new_examples:
    key = (text.strip().lower(), intent)
    if key not in seen:
        data.append({"text": text.strip(), "intent": intent})
        seen.add(key)
        added += 1

print(f"Added {added} new examples (deduplicated).")
print(f"Total: {len(data)}")

from collections import Counter
c = Counter(item["intent"] for item in data)
for cls, count in sorted(c.items()):
    print(f"  {cls}: {count}")

with open(DATA_FILE, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f"\nSaved to {DATA_FILE}")
